# Generated by Django 3.1.14 on 2024-12-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Lat')),
                ('longitude', models.FloatField(verbose_name='Lon')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Appeared at')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Disappeared at')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('health', models.IntegerField(verbose_name='health')),
                ('strength', models.IntegerField(verbose_name='Strength')),
                ('defence', models.IntegerField(verbose_name='Defence')),
                ('stamina', models.IntegerField(verbose_name='Stamina')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon')),
            ],
        ),
    ]
