# Generated by Django 3.1.14 on 2024-12-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared',
            field=models.DateTimeField(null=True, verbose_name='Appeared at'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared',
            field=models.DateTimeField(null=True, verbose_name='Disappeared at'),
        ),
    ]
