# Generated by Django 3.1.14 on 2024-12-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20241215_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='health',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='level',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='stamina',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='strength',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(max_length=400, null=True, verbose_name='Наименование на русском'),
        ),
    ]
